TSDoc updates
mongodb/design pull request #148
Opened 2022-09-09 16:28 UTC by TheSonOfThomp

2022-09-20 20:56 UTC, spark33 requested changes
Small change request to break out one of the large files!

2022-09-20 20:56 UTC, spark33 commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +}
Could we break out the `css` definitions and different functions/components to separate files?

2022-09-30 17:00 UTC, DesignerDave reviewed
Had some notes – mostly code cleanup

2022-09-30 17:00 UTC, DesignerDave commented on components/pages/documentation/TSDocPropTable/TSDocPropsTable.types.ts
> +  return (
Nit – since all we do is return this boolean, this function can be simplified to:

```js
export const isPropItem = (obj: any): obj is PropItem => (
  !isUndefined(obj.name) &&
  !isUndefined(obj.required) &&
  !isUndefined(obj.type) &&
  !isUndefined(obj.description) &&
  !isUndefined(obj.defaultValue)
);
```

We can also perhaps take it a step further:
```js
export const isPropItem = (obj: any): obj is PropItem => [
  obj.name,
  obj.required,
  obj.type,
  obj.description,
  obj.defaultValue,
].every(property => !isUndefined(property));
```

2022-09-30 17:34 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/PropTableSection.tsx
> +        key={doc.displayName}
They're by definition unique in this case, I believe. The display name is the original key used to generate the array

2022-09-30 17:36 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/PropTableTooltipContent.tsx
> +          // This should be default
Not yet. This is the ticket: https://jira.mongodb.org/browse/PD-2424

2022-09-30 17:36 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/PropTableTooltipContent.tsx
> +export const PropTableTooltipContent = ({ prop }: { prop: PropItem }) => (
Ha, that's fair

2022-09-30 17:38 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +        // description={<Markdown>{tsDoc?.description}</Markdown>}
the `ts-ignore` is because currently `description` currently does not accept `ReactNode`

2022-09-30 17:52 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +        // description={<Markdown>{tsDoc?.description}</Markdown>}
We currently have a lot of messy `description` text in TSDoc, so I'm going to just remove this for now

2022-09-30 17:54 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/TSDocPropsTable.types.ts
> +  return (
I like that array method 👍

2022-09-30 18:06 UTC, DesignerDave commented on components/pages/documentation/TSDocPropTable/PropTableSection.tsx
> +        key={doc.displayName}
Sounds good

2022-09-30 18:07 UTC, DesignerDave commented on components/pages/documentation/TSDocPropTable/PropTableTooltipContent.tsx
> +          // This should be default
Ahh okay, thanks!

2022-09-30 19:05 UTC, DesignerDave commented on components/pages/documentation/TSDocPropTable/PropTableTooltipContent.tsx
> +function getDefaultValueString(defaultValue: any): string {
Flagging this type since it's `any` and not a typechecking function. Why does this type need to be so broad?

2022-09-30 19:05 UTC, DesignerDave commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +    content: ')';
Using pseudo-elements here feels a little clever. We should probably just use a STL to add these.

2022-09-30 19:05 UTC, DesignerDave commented on pages/component/[componentName]/documentation.tsx
> +  } = (await getComponent(componentName)) || {
Nit: _Technically_ we should probably use nullish coalescing (`??`) rather than pipes here I think.

2022-09-30 19:47 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +      if (isRequired(a) && !isRequired(z)) return -1;
No, since in the second check we know `a` is not required. If both are required we want to sort in alpha order

2022-09-30 19:58 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/PropTableTooltipContent.tsx
> +function getDefaultValueString(defaultValue: any): string {
Technically should be `PropItem['defaultValue']`, but that itself is typed `any`

2022-09-30 20:00 UTC, TheSonOfThomp commented on pages/component/[componentName]/documentation.tsx
> +  } = (await getComponent(componentName)) || {
You're right 👍

2022-09-30 20:03 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +    content: ')';
Not sure I agree pseudo-elements here is overly clever. This feels like a case they're designed for

2022-09-30 20:18 UTC, DesignerDave commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +      if (isRequired(a) && !isRequired(z)) return -1;
You're right 🤦‍♂️ nevermind!

2022-09-30 20:21 UTC, DesignerDave commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +    content: ')';
I mean technically yes, they are built to be able to do this. Pseudo-elements are also less accessible, and arguably more complex when you're reading the code – for someone looking at the code for the first time, it is certainly harder to know where the parentheses are coming from.

2022-10-03 16:13 UTC, spark33 commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +    content: ')';
I like this approach for when the main text is weirdly positioned or difficult to access because it's dynamically rendered, but that doesn't seem to be the case here. Why would we choose this pseudo-element approach over just adding it to our markup?

2022-10-03 16:17 UTC, spark33 approved these changes
Generally looks good to me! One minor comment on the pseudo-elements on required props.

2022-10-03 16:31 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +    content: ')';
I used pseudo-elements here to keep the formatting in one place. I wasn't sure whether we'd want the parens and/or all-caps, so I used CSS to do this transformation. 

If we're good with the format `(REQUIRED)` I can hard-code that in the markup

2022-10-03 16:36 UTC, spark33 commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +    content: ')';
I'm a little confused. Does text-transform changing the formatting of parens? I thought it would only affect characters in `a-z`. If that's the case, we could move the `()` and keep the rest of the css block as is.

2022-10-03 18:18 UTC, TheSonOfThomp commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +    content: ')';
Also I personally find this hard to read with the parents in the markup:
```jsx
<sup className={requiredHighlightStyle}>(REQUIRED)</sup>
```

2022-10-03 18:19 UTC, DesignerDave commented on components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx
> +    content: ')';
I vastly prefer this TBH. Parentheses are content, not formatting.

2022-10-03 18:20 UTC, merged