PD-2008 Live example
mongodb/design pull request #150
Opened 2022-09-09 17:58 UTC by TheSonOfThomp

2022-09-21 18:15 UTC, spark33 commented
Could we also rename the `example` directory back to `live-example`?

2022-09-26 16:06 UTC, TheSonOfThomp commented
> Could we also rename the `example` directory back to `live-example`?

I named it `example` to match the page name. Why do you recommend changing it back?

2022-09-26 17:36 UTC, spark33 commented
To me, `example` has a different meaning from `live-example`. `live-example` feels like a unique entity as a feature we offer, while `example` feels just like a word, easily replaced by something `sample`. I also associate it with something that's just there for reference, like `env.example`

2022-10-03 18:24 UTC, TheSonOfThomp commented
> To me, `example` has a different meaning from `live-example`. `live-example` feels like a unique entity as a feature we offer, while `example` feels just like a word, easily replaced by something `sample`. I also associate it with something that's just there for reference, like `env.example`

In principle I agree, but I feel since we have `pages/[componentName]/example.tsx` we should also have the `components/pages/example/*` directory. 

Also, to be clear, I don't think we should change the file name in `pages/` since that maps to the URL

2022-10-04 18:57 UTC, spark33 requested changes

2022-10-04 18:57 UTC, spark33 commented on utils/getComponentStory.ts
> +      `@leafygreen-ui/${kebabName}/src/${pascalcase(kebabName)}.story`
There may be some files ending in `stories.tsx`, and there's a case to have `stories` be the standard actually - it's what's used by Storybook

2022-10-04 18:57 UTC, spark33 commented on utils/tsdoc.utils.ts
> +};
🚀🚀🚀

2022-10-04 18:57 UTC, spark33 commented on components/pages/example/KnobRow.tsx
> +    >
There were changes in recent PRs that makes this flexbox mobile responsive - the label and input should stack in mobile. Could we add this in?

2022-10-04 18:57 UTC, spark33 commented on components/pages/example/KnobRow.tsx
> +          </InlineDefinition>
Love this!

2022-10-04 18:57 UTC, spark33 commented on components/pages/example/Knob.tsx
> +      const argOptions = argType?.options
If arguments from the story are being read in like this, I'm wondering if we can rename `argTypes` inside Knob. I would expect this object we're reading from to be something like `{ ...story.argTypes, ...story.args }`, and while I trust that this is being done elsewhere in the codebase, naming it `argTypes` here doesn't make this clear.

2022-10-04 18:57 UTC, spark33 commented on components/pages/example/LiveExample.tsx
> +          const args = { ...meta.args, ...StoryFn?.args };
Yep, here's the overwriting logic - nice. So just renaming the prop in `Knob` would be 👌

2022-10-04 18:57 UTC, spark33 commented on components/pages/example/LiveExample.tsx
> +          // console.log({ meta, args, StoryFn });
Unremoved comment!

2022-10-04 18:57 UTC, spark33 commented on components/pages/example/LiveExample.tsx
> +  );
I don't know if you got this from the React docs or whatever, but this is really smart!

2022-10-04 18:57 UTC, spark33 commented on components/pages/example/LiveExample.tsx
> +      >
Do we not need more logic on this container to maintain things like `z-index` and preventing overflow from whatever is in the StoryFn? Without having tested the rendering of all components, I'm wondering if we need to move over the global CSS from our Storybook config.

2022-10-04 18:57 UTC, spark33 commented on components/pages/example/LiveExample.tsx
> +              args={args}
I find these lines a little confusing - didn't we fold the `argType` fields into `args`? Why do we need to pass `argTypes` separately? Doesn't mean that when we consume `argTypes` in `Knob`, we're not getting the fields in `args`?

2022-10-07 16:46 UTC, TheSonOfThomp commented on package.json
> +    "@leafygreen-ui/typography": "^13.2.0-next.2",
Yeah I need to bump these back to `@latest`

2022-10-07 16:47 UTC, TheSonOfThomp commented on utils/getComponentStory.ts
> +      `@leafygreen-ui/${kebabName}/src/${pascalcase(kebabName)}.story`
We should be consistent with the name, regardless of which one we use

2022-10-07 16:50 UTC, TheSonOfThomp commented on components/pages/example/Knob.tsx
> +      const argOptions = argType?.options
I'd likely rename it to something like `SBArgTypes`, since it comes from the `argTypes` property on Storybook.Meta

2022-10-17 19:31 UTC, spark33 commented on utils/getComponentStory.ts
> +      `@leafygreen-ui/${kebabName}/src/${pascalcase(kebabName)}.story`
Has the standardization already been done? Or will this be breaking for a little while longer for files without names that fit?

If we haven't standardized yet - I feel like `stories.tsx` would be a better name. Ignore if we've already standardized to `story.tsx`.

2022-10-17 19:31 UTC, spark33 approved these changes

2022-10-17 19:43 UTC, TheSonOfThomp commented on utils/getComponentStory.ts
> +      `@leafygreen-ui/${kebabName}/src/${pascalcase(kebabName)}.story`
We're currently using `story.tsx` for everything (except leafygreen-provider)

2022-10-17 19:45 UTC, TheSonOfThomp commented on tsconfig.json
> +  ]
Yeah good catch. I needed to do this to debug, but it should be there

2022-10-18 19:52 UTC, merged