Pd 2357 qa fixes
mongodb/design pull request #158
Opened 2022-09-21 21:02 UTC by spark33

2022-09-27 16:17 UTC, TheSonOfThomp requested changes
Overall looks good 👍 
Just a few small issues.

2022-09-27 16:17 UTC, TheSonOfThomp commented on components/ContentfulRichText/ContentfulRichText.tsx
> +      [BLOCKS.PARAGRAPH]: (node, children) => childrenAreNotEmpty(children) && <Body css={GlobalStyles}>{children}</Body>,
Does mapping this to `undefined` in some cases not lead to errors?

2022-09-27 16:17 UTC, TheSonOfThomp commented on components/ContentfulRichText/ContentfulRichText.tsx
> +      [BLOCKS.PARAGRAPH]: (node, children) => childrenAreNotEmpty(children) && <Body css={GlobalStyles}>{children}</Body>,
Curious where the issue was coming from

2022-09-27 16:17 UTC, TheSonOfThomp commented on components/ContentfulRichText/EmbeddedAsset.tsx
> +  width: -webkit-fill-available;
Will we also need `-moz-available` and `fill-available`?

2022-09-27 16:17 UTC, TheSonOfThomp commented on components/ContentfulRichText/EmbeddedAsset.tsx
> +  width: -webkit-fill-available;
Does `max-content` or `fill-content` work with images?

2022-09-27 16:17 UTC, TheSonOfThomp commented on components/ContentfulRichText/EmbeddedAsset.tsx
> +        // css={{ width }}
remove comment

2022-09-27 16:17 UTC, TheSonOfThomp commented on components/ContentfulRichText/HorizontalLayout.tsx
> +    width: -webkit-fill-available;
I think babel will add this if we use `width: fill-available`

2022-09-27 16:17 UTC, TheSonOfThomp commented on components/Footer.tsx
> +        <p className={trademarkStyle}>© {new Date().getFullYear()} MongoDB, Inc.</p>
Perpetual copyright!!

2022-09-27 16:17 UTC, TheSonOfThomp commented on layouts/ComponentLayout.tsx
> +      // @ts-expect-error
Should remove the `expect-error` and resolve it (I think it's asking for an `aria-label`)

2022-09-27 16:17 UTC, TheSonOfThomp commented on pages/index.tsx
> +  // marginLeft: [`-${spacing[4]}px`, '0px', '0px', '0px'],
remove commented code

2022-09-27 16:17 UTC, TheSonOfThomp commented on styles/globals.tsx
> +export const globalStyles = EmotionReactCss`
Why are we importing 2 instances of `css`?

2022-09-29 18:01 UTC, spark33 commented on components/ContentfulRichText/ContentfulRichText.tsx
> +      [BLOCKS.PARAGRAPH]: (node, children) => childrenAreNotEmpty(children) && <Body css={GlobalStyles}>{children}</Body>,
The issue was that there were empty `<p>` tags rendering, leading to empty spaces that shouldn't have been appearing.

2022-09-29 18:09 UTC, spark33 commented on components/ContentfulRichText/EmbeddedAsset.tsx
> +  width: -webkit-fill-available;
Thanks for catching that! I'll add it in. I'll also try those properties you listed.

2022-09-29 18:11 UTC, spark33 commented on components/Footer.tsx
> +        <p className={trademarkStyle}>© {new Date().getFullYear()} MongoDB, Inc.</p>
Haha yeah I thought about just hard coding this to 2022 as it's usually done, but it was a request from Rob and I assume we'll continue to update Contentful, so I assume it was a valid move

2022-09-29 18:13 UTC, spark33 commented on styles/globals.tsx
> +export const globalStyles = EmotionReactCss`
IIRC, there was a TS issue with someone components that use `css` from `@leafygreen/emotion` that also need to import this `globalStyles` string. It's a weird one for sure, but this was the resolution I found outside of using `&`  at the config level that enables the `css` prop to join the different types for the separate instances of `css`.

2022-09-29 18:24 UTC, spark33 commented on components/ContentfulRichText/ContentfulRichText.tsx
> +      [BLOCKS.PARAGRAPH]: (node, children) => childrenAreNotEmpty(children) && <Body css={GlobalStyles}>{children}</Body>,
Also - I double checked that the `renderNode` function is designed to expect `undefined`! 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/17347644/193112822-f0f90e0b-84a9-4feb-9a20-f7a8156e6a72.png">

2022-10-03 16:16 UTC, TheSonOfThomp approved these changes
There are still a few small issues. I'll approve now, & feel free to merge once those are addressed

2022-10-03 16:16 UTC, TheSonOfThomp commented on components/Footer.tsx
> +import { cx, css } from '@emotion/css';
Should we be using our own emotion import?

2022-10-03 16:16 UTC, TheSonOfThomp commented on components/navigation/NavigationContent.tsx
> +                      activeTab ? activeTab : 'example'
Is this not equivalent?

2022-10-03 16:16 UTC, TheSonOfThomp commented on pages/component/[componentName]/documentation.tsx
> +    <div
Does this need to be in this file? Could this be in Layout?

2022-10-03 16:16 UTC, TheSonOfThomp commented on pages/component/[componentName]/example.tsx
> +        * {
We should avoid using wildcard child selectors

2022-10-03 16:16 UTC, TheSonOfThomp commented on pages/component/[componentName]/guidelines.tsx
> +    <div className={containerPadding}>
Why does each page need different wrapper styling?

2022-10-03 16:16 UTC, TheSonOfThomp commented on styles/globals.tsx
> +export const globalStyles = EmotionReactCss`
I'd try and resolve this. It seems like this might cause more problems down the line

2022-10-03 16:20 UTC, spark33 commented on components/navigation/NavigationContent.tsx
> +                      activeTab ? activeTab : 'example'
Yeah I ran into an instance where `activeTab === ''` and it caused some issues.

2022-10-03 16:22 UTC, spark33 commented on pages/component/[componentName]/documentation.tsx
> +    <div
Not all tabs are going to have the same padding, so we'd need separate definitions.

2022-10-03 16:25 UTC, spark33 commented on styles/globals.tsx
> +export const globalStyles = EmotionReactCss`
If I'm not mistaken, trying to resolve this would mean either touching the `@leafygreen-ui/emotion` package so it plays nicely with `@emotion/...`, or moving all components on the website to `@emotion/...` to we can retire the `@leafygreen-ui/emotion` import. I'm not even sure the latter approach would work, since things could get messed inside LG components.

2022-10-03 16:26 UTC, spark33 commented on pages/component/[componentName]/guidelines.tsx
> +    <div className={containerPadding}>
They'll have different values for padding!

2022-10-03 16:28 UTC, spark33 commented on pages/component/[componentName]/example.tsx
> +        * {
I believe this was to fix an issue where component instances would overflow the Live Example container, so I think it might be appropriate in this situation!

2022-10-03 16:30 UTC, spark33 commented on components/Footer.tsx
> +import { cx, css } from '@emotion/css';
I'll try out the other import. You're right, we should be using `@emotion/...` if it doesn't cause any issues.

2022-10-03 16:30 UTC, merged