LG-3109: React18 + Next13
mongodb/design pull request #285
Opened 2023-07-17 21:04 UTC by shaneeza

2023-07-17 21:42 UTC, shaneeza commented on .eslintrc.cjs
> -    'plugin:react-hooks/recommended',
This was causing this issue
```
Oops! Something went wrong! :(

ESLint: 8.36.0

ESLint couldn't determine the plugin "react-hooks" uniquely.

- /Users/shaneeza.ali/Documents/sites/design/node_modules/eslint-config-next/node_modules/eslint-plugin-react-hooks/index.js (loaded in ".eslintrc.cjs » eslint-config-next » plugin:react-hooks/recommended")
- /Users/shaneeza.ali/Documents/sites/design/node_modules/eslint-plugin-react-hooks/index.js (loaded in ".eslintrc.cjs » plugin:react-hooks/recommended")

Please remove the "plugins" setting from either config or remove either plugin installation.

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

It looks like it is ok to remove since eslint-config-lint uses it. https://nextjs.org/docs/pages/building-your-application/configuring/eslint#eslint-config

2023-07-17 21:42 UTC, shaneeza commented on components/ContentstackRichText/AnnotatedImageBlock/AnnotatedImageBlock.tsx
> +        <Image fill src={entry.image?.url} alt={entry.title} />
No img tag error https://nextjs.org/docs/messages/no-img-element

2023-07-17 21:43 UTC, shaneeza commented on components/NextLinkWrapper.tsx
> -    <a {...props}>{children}</a>
No longer required to pass <a/> tag https://nextjs.org/docs/pages/building-your-application/upgrading/version-13#link-component

2023-07-17 21:43 UTC, shaneeza commented on components/ContentstackRichText/HeaderContent.tsx
> +    // https://nextjs.org/docs/pages/api-reference/components/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag
https://nextjs.org/docs/pages/api-reference/components/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag

2023-08-21 19:04 UTC, spark33 approved these changes

2023-08-22 14:14 UTC, bruugey requested changes
Let's leave this open, but out for now. We need an R17 playground for the time being.

2024-05-20 20:53 UTC, closed without merging